#!/bin/sh
# Load or unload LDD modules at boot
# Uses helper scripts and modprobe for reliable module loading

MODULES="faulty hello"

case "$1" in
    start)
        echo "Loading scull"
	    /usr/bin/scull_load
	
        echo "Loading faulty"
        /usr/bin/module_load faulty
        
        echo "Loading hello"
        /usr/bin/module_load hello
        ;;

    stop)
        echo "Unloading scull"
	    /usr/bin/scull_unload

	    echo "Unloading faulty"
	    /usr/bin/module_unload faulty

	    echo "Unloading scull"
	    /usr/bin/module_unload hello
        ;;

    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

